theme: jekyll-theme-leap-day
title: Nick Morgan
description: >
  Welcome to Nick's Portfolio! <br>
  <a href="mailto:nicolaspmor@gmail.com">nicolaspmor@gmail.com</a>
  <br> <br>
  <a href="https://www.linkedin.com/in/nicolas-p-morgan/">My LinkedIn Profile</a>
