# cli to run:
# bundle exec jekyll serve

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nicolas Morgan
title: BSE Computer Science & Minor Pure Mathematics
email: nicolaspmor@gmail.com
website: github.com/nmorgan8/nmorgan8.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: nicolas-p-morgan
github_username: nmorgan8
# twitter_username: nick_morgan4
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: nick.morgan.794
# flickr_username: jekyll
# instagram_username: nick.morgan8
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Resume
    icon: far fa-file
    url: https://docs.google.com/document/d/1XO_dI7gHJ6DNKQe6vQjQK19WlGDvCYlo/edit?usp=sharing&ouid=109034075234392100349&rtpof=true&sd=true
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nick and I'm currently a Informatics Consultant at Cytokinetics. I am a results-driven Computer Science major currently attending Loyola Marymount University. Aiming for an job or research opportunity that will allow me to utilize my attention to detail, problem-solving, and communication skills to further develop my abilities in the field of computer science.

  I am most skilled in: <mark>Python</mark> and <mark>Eating Pizza</mark>

  If you would like to check out my resume you can click the file icon at top right, or check it out [here](https://docs.google.com/document/d/1XO_dI7gHJ6DNKQe6vQjQK19WlGDvCYlo/edit?usp=sharing&ouid=109034075234392100349&rtpof=true&sd=true)

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Loyola Marymount University
        caption: 2018 - 2022
        sub_title: BSE Computer Science & Minor Pure Mathematics
        quote: >
          "Education breeds confidence. Confidence breeds hope. Hope breeds peace." - Confucius
        description: | # this will include new lines to allow paragraphs
          During my time at LMU I learnt most of my key skills that have I have taken through my career such as communication, teamwork, and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as in the KECK (CS) Lab and Basketball Gym as well as being apart of *Ski and Snowboard Club*
      - layout: top-left
        title: Awards & Honors
        description: |
          - LMU Seaver College of Science and Engineering Dean's List:
            - 2018 - 2021
          - 2nd Place HackerRanker: Git Gud Competition (2019 - open)
          - 3rd Place HackerRank: Git Gud Competition (2020 - upperclassmen)

  - title: Skills & Related Coursework
    layout: list
    content:
      - layout: top-left
        title: Technical Skills
        description: |
          **Programming (or other) Languages**:
          - Python, JavaScript, Java, C++, Swift, HTML5 (markdown), CSS (sheet style)

          **Software & Tools**:
          - Docker, AWS, ReactJS, Google Firebase, Flask, Relational/Document Databases, RESTful architecture, Microsoft Office

      - layout: top-left
        title: Related Coursework
        description: |
          Data Structures, Algorithms, Artificial Intelligence, Cognitive Systems Design, Programming Languages, Databases, Networks and Internets, Computer Systems Organization, Interaction Design, Theory of Computation, Linear Algebra, Calculus (I, II, III), Methods of Proofs, Discrete Methods, Complex Analysis

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Cytokinetics
        link: https://cytokinetics.com/
        # link_text: boringcompany.com
        sub_title: Informatics Consultant
        caption: February 2021 - Present
        quote: >
          Cytokinetics is committed to our mission of developing potential medicines that may improve the healthspan of people living with cardiovascular and neuromuscular diseases of impaired muscle function.
        description: | # this will include new lines to allow paragraphs
          - Migrated legacy, on-premise <mark>Oracle Database</mark> to new <mark>AWS</mark> Postgres Aurora
          - Created new data pipeline scripts in <mark>Python</mark> to replace legacy Oracle Pipeline Pilot.

      - layout: top-left
        title: Loyola Marymount KECK (CS) Lab
        caption: February 2021 - Present
        sub_title: Teaching/Lab Assistant
        quote: >
          "Keck is not a place, it is a people" - Random Keck Regular
        description: |
          - Spring 2021: Algorithms (CMSI 282)
            - Held tutoring session remotely on ZOOM to assist sophomores and juniors taking the course
          - Fall 2021: Computer Programming and Lab (CMSI 1010)
            - Held tutoring sessions in person in CS Lab on campus and help students from all class (CP&L, DS, AI, etc.) who need help learning material

      - layout: top-left
        title: Cytokinetics
        link: https://cytokinetics.com/
        sub_title: Informatics Intern
        caption: May 2019 - August 2019
        description: | # this will include new lines to allow paragraphs
          - Used <mark>Python</mark> to program a <mark>Raspberry Pi</mark> with a camera module that was used to capture images of for data collection and analysis to streamline the drug discovery process. 
          - Started updated-prototyping for legacy inventory management database system.

      - layout: top-left
        title: Mountain Mike's Pizza
        sub_title: Senior Pizza Courier
        caption: Janruary 2018 - June 2018
        description: |
          - Made food, cleaned dishes, delivered pizza, and worked as a cashier. 
          - Responsible for all aspects of customer service and experience.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Schedulion
        link: https://github.com/nmorgan8/schedulion
        link_text: Project Github here
        # additional_links:
        # - title: sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          NCAA Men's Basketball Ranking Prediction and Scheduling Application
        description: | # this will include new lines to allow paragraphs
          A system that can assist LMU's basketball team and coaches in constructing the best schedule of opponent teams for LMU's basketball season.

      - layout: top-middle
        title: Medley
        link: https://github.com/nmorgan8/Medley
        link_text: Project Github here
        quote: >
          A "fruitful" take on a natural language programming language
        description: |
          Medley is a fruitful take on a programming language, with strengths in both enjoyability and ease of use. Medley employs a more natural language approach to programming, all while having a unique theme that makes it both easy and fun to use. The target is for either younger or newer beginning programmers, where a lot of the more complex concepts of programming is simplified by making it similar to English.

      - layout: top-middle
        title: gather
        link: https://gatherweb.vercel.app/
        link_text: Click here for Website
        additional_links:
          - title: Project Github
            icon: fab fa-github
            url: https://github.com/nmorgan8/CMSI-370-Application
        quote: >
          gather is a social media platform that promotes inclusivity, specifically for underrepresented communities.
        description: |
          Gather creates a safe space for there groups to openly communicate and share advice with each out. Gather is only a template and prototype implementation for a potential future full-stack web application.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Blockchain/Web3
      - Skiing
      - Gaming
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/images/profile-pic.jpeg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
