theme: jekyll-theme-leap-day
title: Nick Morgan's Portfolio
description: >
  <a href="mailto:nicolaspmor@gmail.com">nicolaspmor@gmail.com</a>
  ||
  <a href="https://www.linkedin.com/in/nicolas-p-morgan/">My LinkedIn Profile</a>
