# cli to run:
# bundle exec jekyll serve

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nicolas Morgan
title: BSE Computer Science & Minor Pure Mathematics
email: nicolaspmor@gmail.com
# website: github.com/nmorgan8/nmorgan8.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: nicolas-p-morgan
github_username: nmorgan8
# twitter_username: nick_morgan4
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: nick.morgan.794
# flickr_username: jekyll
# instagram_username: nick.morgan8
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Resume
    icon: far fa-file
    url: https://docs.google.com/document/d/1XO_dI7gHJ6DNKQe6vQjQK19WlGDvCYlo/edit?usp=sharing&ouid=109034075234392100349&rtpof=true&sd=true
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# attention to detail, problem-solving, and communication skills

# About Section
# about_title: About Me
about_profile_image: images/profile-pic.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nick and I am graduating this Spring 2022 from Loyola Marymount University. I am also currently working as an Informatics Consultant at Cytokinetics, cyto blurb.

  I am a results-driven Computer Science major aiming for an full-time job opportunity that will give me exposure to the tech industry and allow me to further develop my skills as a computer scientist

  I am most skilled in: <mark>Python</mark> and making dad jokes.

  If you would like to check out my resume you can click the file icon at top right, or check it out [here](https://docs.google.com/document/d/1XO_dI7gHJ6DNKQe6vQjQK19WlGDvCYlo/edit?usp=sharing&ouid=109034075234392100349&rtpof=true&sd=true)

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Loyola Marymount University
        caption: 2018 - 2022
        sub_title: BSE Computer Science & Minor Pure Mathematics
        quote: >
          "Education breeds confidence. Confidence breeds hope. Hope breeds peace." - Confucius

      - layout: top-left
        title: Awards & Honors
        description: |
          - LMU Seaver College of Science and Engineering Dean's List:
            - 2018 - 2021
          - 2nd Place HackerRanker: Git Gud Competition (2019 - open)
          - 3rd Place HackerRank: Git Gud Competition (2020 - upperclassmen)
          - LMU Achievement Award
      - layout: top-left
        title: Extracurriculars
        description: |
          - KECK (CS) Lab - blurb
          - Basketball Gym - blurb
          - *Ski and Snowboard Club* - blurb

  - title: Skills & Related Coursework
    layout: list
    content:
      - layout: top-left
        title: Technical Skills
        description: |
          **Programming (or other) Languages**:
          - Python, JavaScript, Java, C++, Swift, Solidity, HTML5 (markup), CSS (sheet style)

          **Software & Tools**:
          - Docker, AWS, ReactJS, Google Firebase, Flask, Relational/Document Databases, RESTful architecture, Microsoft Office

      - layout: top-left
        title: Related Coursework
        description: |
          Data Structures, Algorithms, Artificial Intelligence, Cognitive Systems Design, Programming Languages, Databases, Networks and Internets, Computer Systems Organization, Interaction Design, Theory of Computation, Linear Algebra, Calculus (I, II, III), Methods of Proofs, Discrete Methods, Complex Analysis

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: Cytokinetics
        link: https://cytokinetics.com/
        sub_title: Informatics Consultant
        caption: February 2021 - Present
        quote: >
          Cytokinetics is committed to our mission of developing potential medicines that may improve the healthspan of people living with cardiovascular and neuromuscular diseases of impaired muscle function.
        description: | # this will include new lines to allow paragraphs
          - Migrated legacy, on-premise <mark>Oracle Database</mark> to new <mark>AWS</mark> Postgres Aurora to help company with future cloud scalability.
          - Created new data pipeline using <mark>Python</mark> to replace current <mark>Oracle Pipeline Pilot</mark>.
            - Coded scripts to replace Cytokinetics' current data pipeline, which allowed Scientists to transfer and store experimental data in the newly created <mark>AWS</mark> database.

      - layout: top-left
        title: Loyola Marymount KECK (CS) Lab
        caption: February 2021 - Present
        sub_title: Teaching/Lab Assistant
        quote: >
          "Keck is not a place, it is a people" - Random Keck Regular
        description: |
          - Spring 2021: Algorithms (CMSI 282)
            - Held remote office hours on ZOOM, 6 hours per week. Coached and assisted sophomores and juniors to help them develop their fundamental algorithmic techniques, including:
              - <mark>Dynamic Programming, BFS, DFS, A* Search, Mini-max Search, Memoization, CSPs, etc</mark>
          - Fall 2021: Computer Programming and Lab (CMSI 1010)
            - Held in person office hours on campus, teaching and mentoring students of all ages who needed help supplemental help.
            - Attended in person classes as a teaching assistant for two different sections to enhance the students learning environment.

      - layout: top-left
        title: Cytokinetics
        link: https://cytokinetics.com/
        sub_title: Informatics Intern
        caption:
          May 2019 - August 2019
          # - Used <mark>Python</mark> to program a <mark>Raspberry Pi</mark> with a camera module that was used to capture images of for data collection and analysis to streamline the drug discovery process.
        description: | # this will include new lines to allow paragraphs
          - Programmed proof-of-concept visual monitoring system, using <mark>Python</mark> and <mark>Raspbery Pi</mark> with a camera module, to provide the Scientists a 24/7 visual imaging to allow scientists to constantly monitor test subjects health and condition.
          - Started prototyping for updating current, legacy inventory management systems to a web application using <mark>Django</mark> and <mark>AWS</mark>.

      - layout: top-left
        title: Mountain Mike's Pizza
        sub_title: Senior Pizza Courier
        caption: Janruary 2018 - June 2018
        description: |
          - Made food, cleaned dishes, delivered pizza, and worked as a cashier. 
          - Responsible for all aspects of customer service and experience.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Schedulion
        link: https://github.com/nmorgan8/schedulion
        link_text: GITHUB PROJECT LINK HERE
        # additional_links:
        # - title: sproogen/modern-resume-theme
        #   icon: fab fa-github
        #   url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          NCAA Men's Basketball Ranking Prediction and Scheduling Application
        description: | # this will include new lines to allow paragraphs
          - Schedulion is a web application that will allow coaches to input their "coaching preferences", for ML model features, as well as a dashboard and schedule building in app features.
          - It's a system that can assist LMU's basketball team and coaches with constructing the best schedule for LMU men's basketball season, in terms of optimizing their NCAA tournament ranking.
          - Model 1: Scrapes NCAA mens basketball team stats to train the model that predicts a teams overall ranking value.
          - Model 2: Uses teams' ranking value, from Model 1, and "coaches preferences" to train Model 2 that will rank/value teams based on which teams that are LMU's statistically "most optimal" matchup.
          - Main Technologies used: <mark>React</mark> for frontend, <mark>Flask</mark> for backend/API, <mark>Google Firestore</mark> for persistent storage, <mark>Scikit</mark> for ML models.

      - layout: top-middle
        title: Medley
        link: https://github.com/nmorgan8/Medley
        link_text: Project Github here
        quote: >
          A "fruitful" take on a natural language programming language
        description: |
          - Medley is a fruitful take on a programming language, using <mark>JavaScript</mark> under the hood, with strengths in both enjoyability and ease of use. 
          - Medley employs a more natural language approach to programming, all while having a unique theme that makes it both easy and fun to use. 
          - The target is for either younger or newer beginning programmers, where a lot of the more complex concepts of programming is simplified by making it similar to English.

      - layout: top-middle
        title: gather
        link: https://gatherweb.vercel.app/
        link_text: Click here for Website
        additional_links:
          - title: Project Github
            icon: fab fa-github
            url: https://github.com/nmorgan8/CMSI-370-Application
        quote: >
          gather is a social media platform that promotes inclusivity, specifically for underrepresented communities.
        description: |
          - Gather creates a safe space for there groups to openly communicate and share advice with each out. 
          - Gather is only a template and prototype implementation for a potential future full-stack web application, using <mark>React</mark>

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Blockchain/Web3
      - Skiing
      - Gaming
# - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
# Look at this cool image
# ![Trees](/images/profile-pic.jpeg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
