# cli to run:
# bundle exec jekyll serve

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nicolas Morgan
title: MS Computer Science | BS Computer Science & Minor Pure Mathematics
email: nicolaspmor@gmail.com
# website: github.com/nmorgan8/nmorgan8.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: nicolas-p-morgan
github_username: nmorgan8
# twitter_username: nick_morgan4
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: nick.morgan.794
# flickr_username: jekyll
# instagram_username: nick.morgan8
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Resume
    icon: far fa-file
    url: https://drive.google.com/file/d/18A_m0SmdiMv6lVgNRn6pW9rHaH9VN96g/view?usp=sharing
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# attention to detail, problem-solving, and communication skills

# About Section
# about_title: About Me
about_profile_image: images/profile_pic.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nick and I graduated, with a MS, in Spring 2023 from Loyola Marymount University. 
  I currently work at Travelers Insurance as an Associate Data Scientist where I had lead a project to develop a novel NLP Deep Learning Neural Network, currently used in production, that predicts various levels of insurance claim severity and currently develop and implement pricing models for countrywide personal and property insurance pricing.
  I concurrently work at a NSF SBIR Phase 1 research startup, MealMate Inc, as the first engineer hired working on primarily on the LLM-based chatbot, initial IOS application desgin and implementation, and AWS backend deployment and production.
  I previously worked as an Adjunct Professor at Loyola Marymount University while completing my Masters in Computer Science with an emphasis in Machine Learning and AI. 

  I am most skilled in: <mark>Python, Machine Learning, AI, and Data Science</mark> and making dad jokes.

  If you would like to check out my resume you can click the file icon at top right, or check it out [here](https://drive.google.com/file/d/18A_m0SmdiMv6lVgNRn6pW9rHaH9VN96g/view?usp=sharing)

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Loyola Marymount University
        caption: 2022 - 2023
        sub_title: MS Computer Science | GPA - 4.00

      - layout: top-middle
        title: Loyola Marymount University
        caption: 2018 - 2022
        sub_title: BS Computer Science & Minor Pure Mathematics | GPA - 3.81
        quote: >
          "Education breeds confidence. Confidence breeds hope. Hope breeds peace." - Confucius

      - layout: top-left
        title: Awards & Honors
        description: |
          - Magna Cum Laude
          - LMU Seaver College of Science and Engineering Dean's List:
            - 2018 - 2022
          - 2nd Place HackerRanker: Git Gud Competition (2019 - open)
          - 3rd Place HackerRank: Git Gud Competition (2020 - upperclassmen)
          - 3rd Place HackerRank: Git Gud Competition (2021 - upperclassmen)
          - LMU Achievement Award
      - layout: top-left
        title: Extracurriculars
        description: |
          - KECK (CS) Lab - TA/Lab Assistant, helped students complete course work and understand the basic programming paradigms, data structures, and algorithms
          - LMU ACM - Loyola Marymount Association for Computing Machinery club member
          - Ski and Snowboard Club - Helped facilited and organize group transportation and trip planning for club members

  - title: Skills & Related Coursework
    layout: list
    content:
      - layout: top-left
        title: Technical Skills
        description: |
          **Programming (or other) Languages**:
          - Python, Swift, JavaScript, Java, C++, Solidity

          **Software & Tools**:
          - TensorFlow, PyTorch, scikit-learn, PyTorch, Numpy, Pandas, Docker, Flask, AWS (SageMaker, EC2, Lambda, RDS, DynamoDB), ReactJS, NodeJS, Google Firebase, Django, SQL/noSQL Databases, RESTful architecture, Microsoft Office

      - layout: top-left
        title: Related Coursework
        description: |
          Machine Learning, Artificial Intelligence, Multi-Agent Systems and Distributed AI, Natural Language Processing, Cognitive Systems Design, Data Science, Data Structures, Algorithms, Natural Language Processing, Software Architecture, Programming Languages, Databases, Networks and Internets, Computer Systems Organization, Interaction Design, Theory of Computation, Linear Algebra, Calculus (I, II, III), Methods of Proofs, Discrete Methods, Complex Analysis

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: MealMate, Inc.
        caption: March 2023 - Present
        sub_title: Software Engineer
        quote: >
          Easily create a better Diet Tracking Experience for everyone, anywhere
        description: |
          - Collaborated closely with the co-founders to define the product roadmap, prioritize features, and architected the frontend, backed, and machine learning AI systems
          - Designed and implemented login and initial pages with functional features for the MVP IOS application
          - Designed MVP and AI food recommender systems, enabling accurate and semantically relevant meal recommendations
          - Responsible for the deployment and maintenance of AWS production server for IOS application backend services
          - Designed and trained machine learning models for meal recommendations, resulting in high performance and accuracy

      - layout: top-left
        title: Travelers Insurance
        caption: September 2023 - Present
        sub_title: Data Scientist
        quote: >
          Travelers takes on the risk and provides the coverage you need to protect the things that are important to you — your home, your car, your valuables and your business — so you don’t have to worry. We have been around for more than 165 years and have earned a reputation as one of the best property casualty insurers in the industry because we take care of our customers.
        description: |
          - Implemented DGLM to model and predict home insurance premiums for dwellings across the Northeast region
          - Developed and implemented new factors and added variables for condo modeling to allow for more accurate premiums
          - Spearheaded implementation of Microsoft Copilot for the PI R&D department
          - Responsible for migration of legacy SAS code and Machine Learning models to updated and modernized Python structure

      - layout: top-left
        title: Loyola Marymount University
        caption: August 2022 - Present
        sub_title: Adjunct Professor
        quote: >
          "99% of the ethical life is being kind to people." - James Martin, S.J.
        description: |
          - Fall 2022: Computer Programming and Lab (CMSI 1010)
            - Presented and helped design two, hour and a half sessions per week to teach the basics paradigms and techniques
            - Taught data structures, basic algorithms, recursion, and object-oriented programming to undergraduate students

      - layout: top-left
        title: Loyola Marymount University
        caption: August 2022 - Mary 2023
        sub_title: Graduate Researcher
        description: |
          - Generative Chatbot
            - Design and implementation of two baseline models, a rule-based approach and information retrieval (IR)-based approach, then an encoder-decoder model to create generative automatic chatbot responses
          - USDA Model Solutions Competition 
            - Identify new approaches to linking Department of Agriculture (USDA) Economic Research Service (ERS)’s Food and Nutrient Database for Dietary Studies (FNDDS) to Information Resources, Inc. (IRI) retail store data in producing the Purchase to Plate Crosswalk (PPC).

      - layout: top-left
        title: Travelers Insurance
        caption: May 2022 - August 2022
        sub_title: Data Scientist/Machine Learning Intern
        quote: >
          Travelers takes on the risk and provides the coverage you need to protect the things that are important to you — your home, your car, your valuables and your business — so you don’t have to worry. We have been around for more than 165 years and have earned a reputation as one of the best property casualty insurers in the industry because we take care of our customers.
        description: |
          - Created a bidirectional LSTM neural network, using <mark>TensorFlow</mark>, to predict insurance claim severity
          - Created two baseline models, Logistic Regression and Naive Bayes (using <mark>SciKit-Learn and Numpy</mark>), to compare advanced Neural Network
          - Used NLP to analyze 100k+ claims with 100+ documents per claim to enhance efficiency of claim professionals
          - Used <mark>AWS SageMaker</mark> environment to implement, modify, and translate between dev and prod environments

      - layout: top-left
        title: Cytokinetics
        link: https://cytokinetics.com/
        sub_title: Data Scientist - Contractor
        caption: February 2021 - April 2022
        quote: >
          Cytokinetics is committed to our mission of developing potential medicines that may improve the healthspan of people living with cardiovascular and neuromuscular diseases of impaired muscle function.
        description: | # this will include new lines to allow paragraphs
          - Analyzed and processed experimental data to find relationships between novel compounds and effects, using <mark>SciKit-Learn<mark>
          - Migrated legacy, on-premise <mark>Oracle Database</mark> to new <mark>AWS</mark> Postgres Aurora to help company with future cloud scalability.
          - Created new data pipeline using <mark>Numpy and Pandas</mark> to replace current <mark>Oracle Pipeline Pilot</mark>.
            - Coded scripts to replace Cytokinetics' current data pipeline, which allowed Scientists to transfer and store experimental data in the newly created <mark>AWS</mark> database.

      - layout: top-left
        title: Loyola Marymount KECK (CS) Lab
        caption: February 2021 - Present
        sub_title: Teaching/Lab Assistant
        quote: >
          "Keck is not a place, it is a people" - Random Keck Regular
        description: |
          - Spring 2021: Algorithms (CMSI 282)
            - Held remote office hours on ZOOM, 6 hours per week. Coached and assisted sophomores and juniors to help them develop their fundamental algorithmic techniques, including:
              - <mark>Dynamic Programming, BFS, DFS, A* Search, Mini-max Search, Memoization, CSPs, etc</mark>
          - Fall 2021: Computer Programming and Lab (CMSI 1010)
            - Held in person office hours on campus, teaching and mentoring students of all ages who needed help supplemental help.
            - Attended in person classes as a teaching assistant for two different sections to enhance the students learning environment.

      - layout: top-left
        title: Cytokinetics
        link: https://cytokinetics.com/
        sub_title: Software Engineering Intern
        caption:
          May 2019 - August 2019
          # - Used <mark>Python</mark> to program a <mark>Raspberry Pi</mark> with a camera module that was used to capture images of for data collection and analysis to streamline the drug discovery process.
        description: | # this will include new lines to allow paragraphs
          - Programmed proof-of-concept visual monitoring system, using <mark>Python, Raspbery Pi, OpenCV, and SciKit-Learn</mark> with a camera module, to provide the Scientists a 24/7 visual imaging to allow scientists to constantly monitor test subjects health and condition.
          - Started prototyping for updating current, legacy inventory management systems to a web application using <mark>Django</mark> and <mark>AWS</mark>.

      - layout: top-left
        title: Mountain Mike's Pizza
        sub_title: Senior Pizza Courier
        caption: Janruary 2018 - June 2018
        description: |
          - Made food, cleaned dishes, delivered pizza, and worked as a cashier. 
          - Responsible for all aspects of customer service and experience.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Artistic Faces
        link: https://huggingface.co/spaces/nmorgan8/ArtisticFaces
        link_text: PROJECT LINK HERE
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/nmorgan8/ArtisticFaces?tab=readme-ov-file
        quote: >
          Image to Image Generative Adversial and Convolutional Neural Networks to transfer historical art styles onto a user's captured image in real-time
        description: | # this will include new lines to allow paragraphs
          - Trained, implemented, and fine-tuned two neural networks on ImageNet, ~50k human faces from ages 10-65, and Wikiart, ~10k images per art movement, image datasets 
          - Two different models were trained and fine-tuned to transfer the historical art style of either impressionism, realism, rococo, romanticism onto the real-time image
          - Eight total models trained to demonstrate effect of CycleGANs vs VGG-16 implementation when dealing with image-to-image transaltaiton and style transfer

      - layout: top-middle
        title: Schedulion
        link: https://schedulion.vercel.app
        link_text: PROJECT LINK HERE
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/nmorgan8/schedulion
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          NCAA Men's Basketball Ranking Prediction and Scheduling Application
        description: | # this will include new lines to allow paragraphs
          - Schedulion is a web application that will allow coaches to input their "coaching preferences", for ML model features, as well as a dashboard and schedule building in app features.
          - It's a system that can assist LMU's basketball team and coaches with constructing the best schedule for LMU men's basketball season, in terms of optimizing their NCAA tournament ranking.
          - Model 1: Scrapes NCAA mens basketball team stats to train the model that predicts a teams overall ranking value.
          - Model 2: Uses teams' ranking value, from Model 1, and "coaches preferences" to train Model 2 that will rank/value teams based on which teams that are LMU's statistically "most optimal" matchup.
            - Main Technologies used: <mark>React</mark> for frontend, <mark>Flask</mark> for backend/API, <mark>Google Firestore</mark> for persistent storage, <mark>Scikit</mark> for ML models, <mark>Vercel & Heroku</mark> for deployment.

      - layout: top-middle
        title: Poker Data Analysis
        link: https://github.com/nmorgan8/Poker
        link_text: Click here for Github
        quote: >
          The Poker data analysis to run biases and correlation between starting hands and the outcome of player.
        description: |
          - Poker data analysis model uses an open-source dataset found on Kaggle.
          - Supervised Learning, Linear Regression and a Multi-layer Perceptron Neural Network to calculate a players expected net profit/loss based on their specific play.
          - Unsupervised Learning, Kmeans to find correlations between starting hands and the net outcome.

      - layout: top-middle
        title: Fake News Classification - Project Green Octopus
        link: https://github.com/lmu-mandy/projects-green-octopus
        link_text: Click here for Github
        quote: >
          Fake News Classifier to process and determine if a news article is from a real source or fake news.
        description: |
          - Fake news data found from an open-source dataset on Kaggle.
          - Baseline Logisitic Regression classifier trained on titles and text of articles of both real and fake
          - Feed-Forward Neural Network built in python using <mark>pytorch</mark>

      - layout: top-middle
        title: Medley
        link: https://github.com/nmorgan8/Medley
        link_text: Project Github here
        quote: >
          A "fruitful" take on a natural language programming language
        description: |
          - Medley is a "fruit themed" take on a programming language, using <mark>JavaScript</mark> under the hood. Its with strengths in both enjoyability and ease of use. 
          - Medley employs a more natural language approach to programming, all while having a unique theme that makes it both easy and fun to use. 
          - Its target audience is with for either younger or beginner programmers, because it simplifies more complex concepts of programming is simplified by making it similar to English.

      - layout: top-middle
        title: gather
        link: https://gatherweb.vercel.app/
        link_text: Click here for Website
        additional_links:
          - title: Project Github
            icon: fab fa-github
            url: https://github.com/nmorgan8/CMSI-370-Application
        quote: >
          gather is a social media platform that promotes inclusivity, specifically for underrepresented communities.
        description: |
          - gather creates a safe space for these groups to openly communicate and share advice with each other. 
          - gather is a prototype for a potential future full-stack web application.
            - Main Technology Used: <mark>React</mark>

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Custom PC Building
      - Blockchain/Web3
      - Skiing
      - Gaming
# - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
# Look at this cool image
# ![Trees](/images/profile-pic.jpeg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
